import type { Database } from "./types";

const hours = (h: number) => new Date(Date.now() + h * 3_600_000).toISOString();

/** Demo data so the app has something to look at on first run. */
export function buildSeed(): Database {
  return {
    users: [
      {
        id: "u_maya",
        name: "Maya Torres",
        role: "buyer",
        location: { city: "Eagle Mountain", state: "UT" },
      },
      {
        id: "u_jordan",
        name: "Jordan Lee",
        role: "buyer",
        location: { city: "Austin", state: "TX" },
      },
      {
        id: "u_cardvault",
        name: "Sam Patel",
        role: "seller",
        sellerType: "company",
        businessName: "Card Vault SLC",
        location: { city: "Salt Lake City", state: "UT" },
        interests: ["charizard", "base set", "evolving skies", "umbreon"],
      },
      {
        id: "u_eli",
        name: "Eli Brooks",
        role: "seller",
        sellerType: "individual",
        location: { city: "Denver", state: "CO" },
        interests: ["pikachu", "151", "umbreon"],
      },
      {
        id: "u_topdeck",
        name: "Rae Kim",
        role: "seller",
        sellerType: "company",
        businessName: "Top Deck Collectibles",
        location: { city: "Phoenix", state: "AZ" },
        interests: ["charizard", "moonbreon", "crown zenith"],
      },
    ],
    wants: [
      {
        id: "w_umbreon",
        buyerId: "u_maya",
        cardName: "Umbreon VMAX",
        setName: "Evolving Skies",
        cardNumber: "215/203",
        tcgCardId: "swsh7-215",
        officialImage: "https://assets.tcgdex.net/en/swsh/swsh7/215",
        rarity: "Secret Rare",
        marketPrice: 2214.79,
        description:
          "Looking for a clean Moonbreon for my binder. Centering matters more to me than the slab label.",
        condition: { kind: "graded", company: "PSA", grade: "10" },
        priceMin: 3800,
        priceMax: 4500,
        scope: "nationwide",
        location: { city: "Eagle Mountain", state: "UT" },
        status: "open",
        createdAt: hours(-20),
        expiresAt: hours(52),
      },
      {
        id: "w_charizard",
        buyerId: "u_jordan",
        cardName: "Charizard",
        setName: "Base Set",
        cardNumber: "4/102",
        tcgCardId: "base1-4",
        officialImage: "https://assets.tcgdex.net/en/base/base1/4",
        rarity: "Rare",
        marketPrice: 944.53,
        description: "Raw copy, no creases. Happy to meet locally if you're in Austin.",
        condition: { kind: "raw", condition: "Lightly Played" },
        priceMin: 700,
        priceMax: 900,
        scope: "local",
        location: { city: "Austin", state: "TX" },
        status: "open",
        createdAt: hours(-6),
        expiresAt: hours(66),
      },
      {
        id: "w_pikachu",
        buyerId: "u_maya",
        cardName: "Pikachu",
        setName: "151",
        cardNumber: "173/165",
        tcgCardId: "sv03.5-173",
        officialImage: "https://assets.tcgdex.net/en/sv/sv03.5/173",
        rarity: "Illustration rare",
        marketPrice: 77.13,
        description: "For my kid's birthday. Near mint raw is perfect.",
        condition: { kind: "raw", condition: "Near Mint" },
        priceMin: 60,
        priceMax: 80,
        scope: "nationwide",
        location: { city: "Eagle Mountain", state: "UT" },
        status: "pending",
        acceptedOfferId: "o_pika_eli",
        createdAt: hours(-50),
        expiresAt: hours(22),
      },
    ],
    offers: [
      {
        id: "o_umb_cv",
        wantId: "w_umbreon",
        sellerId: "u_cardvault",
        price: 4450,
        shipping: 0,
        fulfillment: "local",
        message: "PSA 10, strong centering. Can meet at our shop in SLC.",
        createdAt: hours(-18),
        supersededAt: hours(-4),
      },
      {
        id: "o_umb_td",
        wantId: "w_umbreon",
        sellerId: "u_topdeck",
        price: 4300,
        shipping: 25,
        fulfillment: "ship",
        message: "Insured shipping, ships same day.",
        createdAt: hours(-9),
      },
      {
        id: "o_umb_cv2",
        wantId: "w_umbreon",
        sellerId: "u_cardvault",
        price: 4199,
        shipping: 0,
        fulfillment: "local",
        message: "Dropping to $4,199 for local pickup.",
        createdAt: hours(-4),
      },
      {
        id: "o_pika_eli",
        wantId: "w_pikachu",
        sellerId: "u_eli",
        price: 68,
        shipping: 5,
        fulfillment: "ship",
        message: "Pulled it myself, straight to sleeve and toploader.",
        createdAt: hours(-40),
      },
      {
        id: "o_pika_cv",
        wantId: "w_pikachu",
        sellerId: "u_cardvault",
        price: 74,
        shipping: 0,
        fulfillment: "local",
        message: "",
        createdAt: hours(-44),
      },
    ],
    alerts: [
      {
        id: "a_1",
        sellerId: "u_cardvault",
        wantId: "w_charizard",
        matchedOn: "charizard",
        createdAt: hours(-6),
        read: false,
      },
      {
        id: "a_2",
        sellerId: "u_topdeck",
        wantId: "w_charizard",
        matchedOn: "charizard",
        createdAt: hours(-6),
        read: false,
      },
    ],
  };
}
